In [ ]:
import numpy as np
import torch

In [ ]:
# create a vector of numpy

npArray = np.array([[1, 2, 3, 4, 5]])

print(npArray)

print(npArray.T)

# transpose the numpy array
npArrayT = npArray.T

# Transpose the transposed numpy array
print(npArrayT.T)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [ ]:
# create a vector of torch

torchArray = torch.tensor([[1, 2, 3, 4, 5]])

print(torchArray)

print(torchArray.T)

# transpose the torch array

torchArrayT = torchArray.T

# Transpose the transposed torch array
print(torchArrayT.T)

tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1, 2, 3, 4, 5]])


In [7]:
NDtorchArray = torch.tensor([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]])

print(NDtorchArray)

print(NDtorchArray.T)

# transpose the torch array

NDtorchArrayT = NDtorchArray.T

# Transpose the transposed torch array
print(NDtorchArrayT.T)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])
tensor([[[ 1],
         [ 6]],

        [[ 2],
         [ 7]],

        [[ 3],
         [ 8]],

        [[ 4],
         [ 9]],

        [[ 5],
         [10]]])
tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])
