In [1]:
import numpy as np
import torch

In [2]:
''' 
to multiply two tensors, the number of columns in the first tensor must be equal to the number of rows in the second tensor
and the result will have the same number of rows as the first tensor and the same number of columns as the second tensor
'''
# example: 2x3 * 3x2 = 2x2, 5x3 * 3x2 = 5x2

# if a = 4 * 5 and b = 7 * 4, then a * b is not possible

a = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2x3

b = torch.tensor([[7, 8], [9, 10], [11, 12]]) # 3x2

c = torch.mm(a, b) # 2x2

print(c)


tensor([[ 58,  64],
        [139, 154]])


In [9]:
a = np.random.randn(10, 5) # 10x5

b = np.random.randn(5, 3) # 5x13   

c = np.dot(a, b) # 5x2

print(c)

[[-0.94253455 -1.61722132  3.65387169]
 [-1.33834729  1.71657351  2.20872812]
 [ 0.1475974   0.07701213 -7.18949552]
 [-0.80132801 -1.86121014  0.85882197]
 [-0.75432509  1.61219358  0.59925529]
 [ 0.06187302 -0.1683555   2.68546749]
 [ 0.22053088 -0.90556089  0.46490178]
 [-0.68129779 -0.5051298   3.0187079 ]
 [-0.39827275  0.5270064  -0.19388476]
 [ 2.99104976 -2.20854567 -0.49056572]]
